services:
  backend:
    build:
      context: ./backend
    container_name: journeyledger-backend
    ports:
      - "8080:8080"
    env_file:
      - .env.development

  frontend:
    build:
      context: ./frontend
    container_name: journeyledger-frontend
    ports:
      - "5173:80"
