name: Deploy JourneyLedger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on:
      - self-hosted
      - Linux
      - ARM

    steps:
      - name: Deploy application
        run: |
          echo "Deploy workflow picked up"
          cd /home/pi/personalDev/JourneyLedger
          pwd
          ls -la