name: Deploy JourneyLedger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: 
      - selft-hosted
      - Linux
      - ARM

    steps:
      - name: Deploy application
        run: |
          cd /home/pi/personalDev/JourneyLedger
          ./deploy.sh