name: Runner Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on:
      - self-hosted
      - Linux
      - ARM

    steps:
      - name: Test runner
        run: |
          echo "Runner is working"
          hostname
          pwd